[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_event = 'BufRead'
hook_add = '''
    autocmd initvim FileType denite call s:denite_my_settings()
    function! s:denite_my_settings() abort
        nnoremap <silent><buffer><expr> <CR>
        \ denite#do_map('do_action')
        nnoremap <silent><buffer><expr> p
        \ denite#do_map('do_action', 'preview')
        nnoremap <silent><buffer><expr> q
        \ denite#do_map('quit')
        nnoremap <silent><buffer><expr> i
        \ denite#do_map('open_filter_buffer')
        nnoremap <silent><buffer><expr> <Space>
        \ denite#do_map('toggle_select').'j'
    endfunction
"    noremap <Leader>f :Denite file<CR>
    noremap <Leader>s :Denite file/rec<CR>
    noremap <Leader>b :Denite buffer<CR>
    noremap <Leader>g :Denite grep<CR>
'''
hook_post_source = '''
    " denite file/rec
    let s:ignore_globs = ['.git', '.svn', 'node_modules']
    call denite#custom#var('file/rec', 'command', [
          \ 'ag',
          \ '--follow',
          \ ] + map(deepcopy(s:ignore_globs), { k, v -> '--ignore=' . v }) + [
          \ '--nocolor',
          \ '--nogroup',
          \ '-g',
          \ ''
          \ ])
    call denite#custom#source('file/rec', 'matchers', ['matcher/substring'])
    call denite#custom#filter('matcher/ignore_globs', 'ignore_globs', s:ignore_globs)

    " denite grep
    call denite#custom#var('grep', 'command', ['ag'])
    call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
    call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'pattern_opt', [])
    call denite#custom#var('grep', 'separator', ['--'])
    call denite#custom#var('grep', 'final_opts', [])
'''

